"""Unit tests for forge_prep/near_dup.py — MinHash + LSH near-duplicate detection."""

import unittest

from forge_prep import near_dup

DOC_A = """
Quarterly Business Review — Q3 2026

The enterprise segment delivered strong growth this quarter, driven primarily by expansion within
existing accounts rather than new logo acquisition. Net revenue retention climbed to 118 percent,
up from 109 percent in the prior quarter, reflecting successful upsell motions across the customer
base. The professional services team closed the quarter with a healthy backlog, and the product
organization shipped three major features ahead of schedule: the unified analytics dashboard, the
role-based access control overhaul, and the new billing reconciliation engine.

Customer churn remained flat at 2.1 percent, in line with historical averages. The support team
resolved 94 percent of tickets within SLA, a slight improvement over last quarter. Engineering
velocity increased as the platform team completed the migration to the new deployment pipeline,
cutting average release time from six hours to ninety minutes.
""".strip()

DOC_B_HEADER_FOOTER = (
    "CONFIDENTIAL — INTERNAL USE ONLY\n\n" + DOC_A +
    "\n\n---\nGenerated by Acme Reporting Suite v4.2 on 2026-10-14."
)

DOC_C_UNRELATED = """
Engineering Design Doc — Storage Layer Migration

This document proposes moving our primary storage layer from a single-region relational database
to a multi-region distributed key-value store. The current architecture has served us well but is
approaching its scaling limits: write throughput during peak hours regularly exceeds eighty percent
of provisioned capacity, and failover testing has revealed unacceptable recovery times during
simulated region outages. The proposed migration would introduce a new abstraction layer between
application code and storage, allowing us to gradually shift traffic without a hard cutover.
""".strip()


class TestShingleText(unittest.TestCase):
    def test_produces_five_word_shingles(self):
        shingles = near_dup.shingle_text("the quick brown fox jumps over the lazy dog")
        self.assertIn("the quick brown fox jumps", shingles)
        self.assertIn("fox jumps over the lazy", shingles)
        self.assertIn("jumps over the lazy dog", shingles)

    def test_case_folded(self):
        a = near_dup.shingle_text("The Quick Brown Fox Jumps")
        b = near_dup.shingle_text("the quick brown fox jumps")
        self.assertEqual(a, b)

    def test_whitespace_normalized(self):
        a = near_dup.shingle_text("the  quick\tbrown\nfox   jumps")
        b = near_dup.shingle_text("the quick brown fox jumps")
        self.assertEqual(a, b)

    def test_empty_text_returns_empty_set(self):
        self.assertEqual(near_dup.shingle_text(""), set())

    def test_text_shorter_than_k_returns_single_shingle(self):
        shingles = near_dup.shingle_text("only three words")
        self.assertEqual(shingles, {"only three words"})

    def test_shingle_count_matches_formula(self):
        text = " ".join(f"word{i}" for i in range(20))
        shingles = near_dup.shingle_text(text, k=5)
        self.assertEqual(len(shingles), 20 - 5 + 1)


class TestMinhashSignature(unittest.TestCase):
    def test_signature_length_matches_num_perm(self):
        sig = near_dup.minhash_signature(near_dup.shingle_text(DOC_A))
        self.assertEqual(len(sig), near_dup.NUM_PERM)

    def test_deterministic_across_calls(self):
        shingles = near_dup.shingle_text(DOC_A)
        sig1 = near_dup.minhash_signature(shingles)
        sig2 = near_dup.minhash_signature(shingles)
        self.assertEqual(sig1, sig2)

    def test_empty_shingles_returns_max_value_signature(self):
        sig = near_dup.minhash_signature(set())
        self.assertEqual(len(sig), near_dup.NUM_PERM)
        self.assertTrue(all(v == near_dup._MASK64 for v in sig))

    def test_identical_documents_have_identical_signatures(self):
        sig_a = near_dup.minhash_signature(near_dup.shingle_text(DOC_A))
        sig_a2 = near_dup.minhash_signature(near_dup.shingle_text(DOC_A))
        self.assertEqual(sig_a, sig_a2)


class TestShingleCapping(unittest.TestCase):
    """
    Worst-case per-file minhash cost is bounded by MAX_SHINGLES regardless
    of document size (measured: a single 62,855-shingle 2.5MB file dropped
    from 1.36s to well under 0.1s after capping). The default value (2000)
    and the recall/precision/runtime tradeoff behind it are measured in
    tests/fixtures/measure_shingle_cap.py against real >200KB documents
    with known Jaccard — see docs/methodology.md for the full table.
    """

    def test_bounded_shingle_hashes_caps_large_inputs(self):
        many_shingles = {f"shingle number {i} of many unique ones" for i in range(10_000)}
        hashes = near_dup._bounded_shingle_hashes(many_shingles)
        self.assertEqual(len(hashes), near_dup.MAX_SHINGLES)

    def test_zero_or_negative_max_shingles_means_uncapped(self):
        many_shingles = {f"shingle number {i} of many unique ones" for i in range(3_000)}
        self.assertEqual(len(near_dup._bounded_shingle_hashes(many_shingles, max_shingles=0)), 3_000)
        self.assertEqual(len(near_dup._bounded_shingle_hashes(many_shingles, max_shingles=-1)), 3_000)

    def test_bounded_shingle_hashes_passes_through_small_inputs(self):
        few_shingles = {f"shingle {i}" for i in range(10)}
        hashes = near_dup._bounded_shingle_hashes(few_shingles)
        self.assertEqual(len(hashes), 10)

    def test_bounded_shingle_hashes_is_deterministic(self):
        many_shingles = {f"shingle number {i} of many unique ones" for i in range(10_000)}
        first = near_dup._bounded_shingle_hashes(many_shingles)
        second = near_dup._bounded_shingle_hashes(many_shingles)
        self.assertEqual(sorted(first), sorted(second))

    def test_capping_does_not_prevent_large_near_duplicates_from_clustering(self):
        # A large (> MAX_SHINGLES) document and its header/footer variant
        # should still cluster correctly after capping.
        big_body = " ".join(f"paragraph{i} contains some unique filler words here today" for i in range(500))
        variant = "REPORT HEADER\n\n" + big_body + "\n\nEND OF REPORT"
        sig_a = near_dup.minhash_signature(near_dup.shingle_text(big_body))
        sig_b = near_dup.minhash_signature(near_dup.shingle_text(variant))
        self.assertGreaterEqual(near_dup.estimate_jaccard(sig_a, sig_b), 0.85)


class TestEstimateJaccard(unittest.TestCase):
    def test_identical_signatures_give_jaccard_one(self):
        sig = near_dup.minhash_signature(near_dup.shingle_text(DOC_A))
        self.assertEqual(near_dup.estimate_jaccard(sig, sig), 1.0)

    def test_near_duplicate_documents_score_high(self):
        sig_a = near_dup.minhash_signature(near_dup.shingle_text(DOC_A))
        sig_b = near_dup.minhash_signature(near_dup.shingle_text(DOC_B_HEADER_FOOTER))
        self.assertGreaterEqual(near_dup.estimate_jaccard(sig_a, sig_b), 0.85)

    def test_unrelated_documents_score_low(self):
        sig_a = near_dup.minhash_signature(near_dup.shingle_text(DOC_A))
        sig_c = near_dup.minhash_signature(near_dup.shingle_text(DOC_C_UNRELATED))
        self.assertLess(near_dup.estimate_jaccard(sig_a, sig_c), 0.2)

    def test_estimate_is_close_to_true_jaccard(self):
        sh_a = near_dup.shingle_text(DOC_A)
        sh_b = near_dup.shingle_text(DOC_B_HEADER_FOOTER)
        true_jaccard = len(sh_a & sh_b) / len(sh_a | sh_b)
        sig_a = near_dup.minhash_signature(sh_a)
        sig_b = near_dup.minhash_signature(sh_b)
        estimated = near_dup.estimate_jaccard(sig_a, sig_b)
        self.assertLess(abs(true_jaccard - estimated), 0.1)

    def test_mismatched_length_returns_zero(self):
        self.assertEqual(near_dup.estimate_jaccard([1, 2, 3], [1, 2]), 0.0)

    def test_empty_signatures_return_zero(self):
        self.assertEqual(near_dup.estimate_jaccard([], []), 0.0)


class TestFindClusters(unittest.TestCase):
    def _sig(self, text):
        return near_dup.minhash_signature(near_dup.shingle_text(text))

    def test_near_duplicates_cluster_together(self):
        signatures = {
            "a": self._sig(DOC_A),
            "b": self._sig(DOC_B_HEADER_FOOTER),
            "c": self._sig(DOC_C_UNRELATED),
        }
        clusters = near_dup.find_clusters(signatures, threshold=0.85)
        self.assertEqual(clusters, [["a", "b"]])

    def test_no_clusters_when_all_documents_distinct(self):
        signatures = {
            "a": self._sig(DOC_A),
            "c": self._sig(DOC_C_UNRELATED),
        }
        clusters = near_dup.find_clusters(signatures, threshold=0.85)
        self.assertEqual(clusters, [])

    def test_transitive_clustering_via_union_find(self):
        # b is a near-dup of a; c is a near-dup of b (but maybe not as close
        # to a directly) — all three should end up in one connected cluster.
        variant_1 = "Note: v1.\n\n" + DOC_A
        variant_2 = "Note: v2, reviewed.\n\n" + DOC_A
        signatures = {
            "a": self._sig(DOC_A),
            "v1": self._sig(variant_1),
            "v2": self._sig(variant_2),
        }
        clusters = near_dup.find_clusters(signatures, threshold=0.85)
        self.assertEqual(len(clusters), 1)
        self.assertEqual(set(clusters[0]), {"a", "v1", "v2"})

    def test_singleton_documents_are_not_returned_as_clusters(self):
        signatures = {"only": self._sig(DOC_A)}
        clusters = near_dup.find_clusters(signatures, threshold=0.85)
        self.assertEqual(clusters, [])

    def test_empty_input(self):
        self.assertEqual(near_dup.find_clusters({}), [])

    def test_unrelated_documents_never_become_lsh_candidates(self):
        # find_clusters only ever compares pairs that already share an LSH
        # band. Genuinely unrelated documents essentially never share one
        # (matching all 8 values in a band by chance is astronomically
        # unlikely), so no threshold — not even 0.0 — retroactively
        # clusters them. That's LSH doing its job: avoiding full O(n^2)
        # pairwise comparison, not a bug.
        signatures = {
            "a": self._sig(DOC_A),
            "c": self._sig(DOC_C_UNRELATED),
        }
        clusters = near_dup.find_clusters(signatures, threshold=0.0)
        self.assertEqual(clusters, [])

    def test_higher_threshold_is_stricter(self):
        signatures = {
            "a": self._sig(DOC_A),
            "b": self._sig(DOC_B_HEADER_FOOTER),
        }
        clusters_loose = near_dup.find_clusters(signatures, threshold=0.5)
        clusters_strict = near_dup.find_clusters(signatures, threshold=0.999)
        self.assertEqual(len(clusters_loose), 1)
        self.assertEqual(len(clusters_strict), 0)


if __name__ == "__main__":
    unittest.main()
