"""
Readiness Report — generates Markdown and JSON reports
from audit results and readiness scores.
"""

import json
from pathlib import Path
from forge_prep.auditor import CorpusAuditResult
from forge_prep.scorer import ReadinessScore


class ReadinessReport:
    """Generates human-readable and machine-readable reports."""

    def __init__(self, audit: CorpusAuditResult, score: ReadinessScore):
        self.audit = audit
        self.score = score

    def to_markdown(self) -> str:
        a = self.audit
        s = self.score
        mb = a.total_size_bytes / 1024 / 1024

        lines = [
            f"# Forge Readiness Report",
            f"",
            f"**Corpus:** `{a.corpus_path}`",
            f"**Timestamp:** {a.timestamp}",
            f"**Overall Score:** {s.overall}/100 (Grade: **{s.grade}**)",
            f"",
            f"> {s.forge_recommendation}",
            f"",
            f"---",
            f"",
            f"## Corpus Overview",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total files | {a.total_files:,} |",
            f"| Total size | {mb:.1f} MB |",
            f"| Estimated tokens | {a.total_tokens_estimate:,} |",
            f"| Duplicates | {a.duplicate_count:,} ({a.duplicate_count / max(a.total_files, 1) * 100:.1f}%) |",
            f"| Files with PII | {a.pii_files_count:,} |",
            f"",
            f"## Dimension Scores",
            f"",
            f"| Dimension | Score | Weight | Details |",
            f"|-----------|-------|--------|---------|",
        ]

        for d in s.dimensions:
            bar = self._score_bar(d.score)
            lines.append(f"| {d.name} | {bar} {d.score:.0f} | {d.weight:.0%} | {d.details} |")

        lines.extend([
            f"",
            f"## File Types",
            f"",
        ])
        for ext, count in sorted(a.file_type_distribution.items(), key=lambda x: -x[1]):
            pct = count / max(a.total_files, 1) * 100
            lines.append(f"- `{ext}`: {count} files ({pct:.1f}%)")

        lines.extend([
            f"",
            f"## Languages Detected",
            f"",
        ])
        for lang, count in sorted(a.language_distribution.items(), key=lambda x: -x[1]):
            pct = count / max(a.total_files, 1) * 100
            lines.append(f"- **{lang}**: {count} files ({pct:.1f}%)")

        if a.recommendations:
            lines.extend([
                f"",
                f"## Recommendations",
                f"",
            ])
            for i, rec in enumerate(a.recommendations, 1):
                lines.append(f"{i}. {rec}")

        lines.extend([
            f"",
            f"---",
            f"*Generated by [forge-prep](https://github.com/kris/forge-prep) v0.1.0*",
        ])

        return "\n".join(lines)

    def to_json(self) -> dict:
        return {
            "audit": self.audit.to_dict(),
            "score": self.score.to_dict(),
        }

    def save(self, output_dir: str):
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        # Markdown report
        md_path = out / "forge_readiness_report.md"
        md_path.write_text(self.to_markdown(), encoding="utf-8")

        # JSON report (for dashboard)
        json_path = out / "forge_readiness_report.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(self.to_json(), f, indent=2, ensure_ascii=False)

        return md_path, json_path

    @staticmethod
    def _score_bar(score: float) -> str:
        filled = int(score / 10)
        empty = 10 - filled
        return "█" * filled + "░" * empty
