"""
Readiness Report — generates Markdown and JSON reports
from audit results and readiness scores.
"""

import json
from pathlib import Path

from forge_prep._version import get_version
from forge_prep.auditor import CorpusAuditResult
from forge_prep.scorer import ReadinessScore


class ReadinessReport:
    """Generates human-readable and machine-readable reports."""

    def __init__(self, audit: CorpusAuditResult, score: ReadinessScore):
        self.audit = audit
        self.score = score

    def to_markdown(self) -> str:
        a = self.audit
        s = self.score
        mb = a.total_size_bytes / 1024 / 1024

        lines = [
            "# Forge Readiness Report",
            "",
            f"**Corpus:** `{a.corpus_path}`",
            f"**Timestamp:** {a.timestamp}",
            f"**Overall Score:** {s.overall}/100 (Grade: **{s.grade}**)",
            "",
            f"> {s.forge_recommendation}",
            "",
            "---",
            "",
            "## Corpus Overview",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Total files | {a.total_files:,} |",
            f"| Total size | {mb:.1f} MB |",
            f"| Estimated tokens | {self._token_estimate_display(a)} |",
            f"| Duplicates | {a.duplicate_count:,} ({a.duplicate_count / max(a.total_files, 1) * 100:.1f}%) |",
            f"| Files with PII | {a.pii_files_count:,} |",
            "",
            "## Dimension Scores",
            "",
            "| Dimension | Score | Weight | Details |",
            "|-----------|-------|--------|---------|",
        ]

        for d in s.dimensions:
            bar = self._score_bar(d.score)
            lines.append(f"| {d.name} | {bar} {d.score:.0f} | {d.weight:.0%} | {d.details} |")

        lines.extend([
            "",
            "## File Types",
            "",
        ])
        for ext, count in sorted(a.file_type_distribution.items(), key=lambda x: -x[1]):
            pct = count / max(a.total_files, 1) * 100
            lines.append(f"- `{ext}`: {count} files ({pct:.1f}%)")

        lines.extend([
            "",
            "## Languages Detected",
            "",
        ])
        for lang, count in sorted(a.language_distribution.items(), key=lambda x: -x[1]):
            pct = count / max(a.total_files, 1) * 100
            lines.append(f"- **{lang}**: {count} files ({pct:.1f}%)")

        if a.recommendations:
            lines.extend([
                "",
                "## Recommendations",
                "",
            ])
            for i, rec in enumerate(a.recommendations, 1):
                lines.append(f"{i}. {rec}")

        lines.extend([
            "",
            "---",
            f"*Generated by [forge-prep](https://github.com/satoshi-kris/forge-prep) v{get_version()}*",
        ])

        return "\n".join(lines)

    def to_json(self) -> dict:
        return {
            "audit": self.audit.to_dict(),
            "score": self.score.to_dict(),
        }

    def save(self, output_dir: str):
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        # Markdown report
        md_path = out / "forge_readiness_report.md"
        md_path.write_text(self.to_markdown(), encoding="utf-8")

        # JSON report (for dashboard)
        json_path = out / "forge_readiness_report.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(self.to_json(), f, indent=2, ensure_ascii=False)

        return md_path, json_path

    @staticmethod
    def _score_bar(score: float) -> str:
        filled = int(score / 10)
        empty = 10 - filled
        return "█" * filled + "░" * empty

    @staticmethod
    def _token_estimate_display(audit: CorpusAuditResult) -> str:
        if audit.tokens_estimate_uncertain:
            return (
                f"{audit.total_tokens_estimate:,} — **uncertain**, range "
                f"{audit.total_tokens_estimate_low:,}–{audit.total_tokens_estimate_high:,} "
                f"(some file types have >25% measured error, see docs/methodology.md)"
            )
        return f"{audit.total_tokens_estimate:,}"
