"""
One-off measurement script — not part of the test suite, not run in CI.

Measures recall/precision lost to MAX_SHINGLES capping on genuinely large
(>200KB) real documents, where the cap actually binds (every test fixture
in tests/test_near_dup.py is small enough that it never engages the cap).

Ground truth: 7 real books (Project Gutenberg, boilerplate stripped),
each turned into 5 variants (5%/10%/20%/30% of paragraphs replaced with
unrelated content from a different book, plus a header/footer-only edit)
= 35 (original, variant) pairs. True Jaccard is computed directly on the
full, uncapped shingle sets. For each candidate cap, MinHash signatures
are computed at that cap and run through the real find_clusters() pairwise,
so this measures the actual detection pipeline, not just raw signature
noise.

Usage:
    python3 tests/fixtures/measure_shingle_cap.py /path/to/book/dir
The directory should contain at least 2 plain-text files, each >200KB,
with Gutenberg (or similar) boilerplate headers/footers already stripped —
not checked into this repo, since it's a one-off measurement, not a
fixture the test suite depends on. The results this script produced were
generated from 7 books fetched from Project Gutenberg (Pride and
Prejudice, Frankenstein, The Adventures of Sherlock Holmes, A Tale of Two
Cities, The Picture of Dorian Gray, Moby Dick, Dracula — all public
domain), with each file's "*** START OF ... ***" / "*** END OF ... ***"
markers used to slice out just the novel text.
"""

import random
import sys
import zlib
from pathlib import Path

from forge_prep import near_dup

CHANGE_LEVELS = [0.05, 0.10, 0.20, 0.30]
CAPS_TO_TEST = [150, 250, 500, 2000, 0]  # 0 = uncapped
THRESHOLD = near_dup.DEFAULT_THRESHOLD


def split_paragraphs(text: str) -> list:
    paras = [p.strip() for p in text.split("\n\n")]
    return [p for p in paras if p]


def make_paragraph_variant(paragraphs: list, filler_paragraphs: list, fraction: float, seed: int) -> str:
    rng = random.Random(seed)
    n_change = max(1, int(len(paragraphs) * fraction))
    indices = sorted(rng.sample(range(len(paragraphs)), min(n_change, len(paragraphs))))
    filler_pool = list(filler_paragraphs)
    rng.shuffle(filler_pool)
    result = list(paragraphs)
    for i, idx in enumerate(indices):
        result[idx] = filler_pool[i % len(filler_pool)]
    return "\n\n".join(result)


def make_header_footer_variant(text: str) -> str:
    return (
        "INTERNAL DRAFT — DO NOT DISTRIBUTE\nRevision 3, reviewed 2026-08-02\n\n"
        + text
        + "\n\n---\nEnd of document. Generated by Acme Publishing Pipeline v2.1."
    )


def true_jaccard(text_a: str, text_b: str) -> float:
    sh_a = near_dup.shingle_text(text_a)
    sh_b = near_dup.shingle_text(text_b)
    if not sh_a and not sh_b:
        return 1.0
    return len(sh_a & sh_b) / len(sh_a | sh_b)


def build_pairs(book_dir: Path) -> list:
    files = sorted(book_dir.glob("*.txt"))
    assert len(files) >= 2, f"need at least 2 base books in {book_dir}, found {len(files)}"
    texts = {f.stem: f.read_text(encoding="utf-8", errors="replace") for f in files}
    for name, t in texts.items():
        assert len(t.encode("utf-8")) > 200_000, f"{name} is only {len(t)} bytes, need >200KB"

    pairs = []  # (pair_id, original_text, variant_text, true_jaccard)
    names = list(texts.keys())
    for i, name in enumerate(names):
        base = texts[name]
        base_paragraphs = split_paragraphs(base)
        other_name = names[(i + 1) % len(names)]
        filler_paragraphs = split_paragraphs(texts[other_name])

        for level in CHANGE_LEVELS:
            # Python's built-in hash() of strings is randomized per-process
            # (PYTHONHASHSEED) — using it for a "deterministic" seed here
            # would silently make every run generate different variant
            # documents. zlib.crc32 is stable across processes.
            seed = zlib.crc32(f"{name}:{level}".encode())
            variant = make_paragraph_variant(base_paragraphs, filler_paragraphs, level, seed=seed)
            pairs.append((f"{name}_change{int(level * 100)}pct", base, variant))

        hf_variant = make_header_footer_variant(base)
        pairs.append((f"{name}_header_footer", base, hf_variant))

    return pairs


def evaluate_at_cap(pairs: list, cap: int) -> dict:
    # near_dup._bounded_shingle_hashes treats max_shingles <= 0 as uncapped natively.
    tp = fp = fn = tn = 0
    for pair_id, orig, variant, tj in pairs:
        sig_a = near_dup.minhash_signature(near_dup.shingle_text(orig), max_shingles=cap)
        sig_b = near_dup.minhash_signature(near_dup.shingle_text(variant), max_shingles=cap)
        clusters = near_dup.find_clusters({"a": sig_a, "b": sig_b}, threshold=THRESHOLD)
        predicted_dup = len(clusters) == 1
        actual_dup = tj >= THRESHOLD
        if actual_dup and predicted_dup:
            tp += 1
        elif actual_dup and not predicted_dup:
            fn += 1
        elif not actual_dup and predicted_dup:
            fp += 1
        else:
            tn += 1
    precision = tp / (tp + fp) if (tp + fp) else float("nan")
    recall = tp / (tp + fn) if (tp + fn) else float("nan")
    return {"tp": tp, "fp": fp, "fn": fn, "tn": tn, "precision": precision, "recall": recall}


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    book_dir = Path(sys.argv[1])

    print("Building (original, variant) pairs from real >200KB books...")
    pairs_raw = build_pairs(book_dir)
    print(f"Built {len(pairs_raw)} pairs\n")

    print("Computing true Jaccard on full, uncapped shingle sets...")
    pairs = []
    for pair_id, orig, variant in pairs_raw:
        tj = true_jaccard(orig, variant)
        pairs.append((pair_id, orig, variant, tj))
        print(f"  {pair_id:40s} true_jaccard={tj:.4f} {'(near-dup)' if tj >= THRESHOLD else '(not near-dup)'}")

    n_true_dup = sum(1 for _, _, _, tj in pairs if tj >= THRESHOLD)
    print(f"\n{len(pairs)} pairs total, {n_true_dup} are true near-duplicates at threshold {THRESHOLD}, "
          f"{len(pairs) - n_true_dup} are not (both are useful ground truth)\n")

    print("=" * 90)
    print(f"{'cap':>8s} {'tp':>4s} {'fp':>4s} {'fn':>4s} {'tn':>4s} {'precision':>10s} {'recall':>8s}")
    print("=" * 90)
    results = {}
    for cap in CAPS_TO_TEST:
        r = evaluate_at_cap(pairs, cap)
        results[cap] = r
        label = "uncapped" if cap == 0 else str(cap)
        print(f"{label:>8s} {r['tp']:4d} {r['fp']:4d} {r['fn']:4d} {r['tn']:4d} {r['precision']:10.3f} {r['recall']:8.3f}")

    return results


if __name__ == "__main__":
    main()
